# DEV

# Use Node.js as the base image
FROM node:21

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all of your app's source code
COPY . .

# Copy webpack.config to /node_modules
COPY ./webpack.config.js ./node_modules/react-scripts/config/

# Expose port 3000
EXPOSE 3000

# Command to start the application
CMD ["npm", "start"]
