# PROD

FROM python:3.8

# Install system dependencies including Poppler
RUN apt-get update && \
  apt-get install -y poppler-utils && \
  apt-get clean
  
WORKDIR /app/backend

COPY requirements.txt ./

RUN pip install -r requirements.txt

RUN PYTHONDONTWRITEBYTECODE=1

COPY . ./

EXPOSE 8000